import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fontsource/inter";
import EmotionRegistry from "@/lib/EmotionRegistry";
import ThemeRegistry from "@/components/ThemeRegistry";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <EmotionRegistry>
                    <ThemeRegistry>{children}</ThemeRegistry>
                </EmotionRegistry>
            </body>
        </html>
    );
}
