/**
 * Anime Seeder
 * Seeds the P - Animes content type with sample data
 */

import type { Core } from "@strapi/strapi";

export interface AnimeData {
    position?: number;
    name: string;
    date?: string;
    description?: string;
    has_conclusion?: boolean;
}

const animeSeeds: AnimeData[] = [
    {
        position: 1,
        name: "naruto shippuden",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: true,
    },
    {
        position: 2,
        name: "sakura card captor",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: true,
    },
    {
        position: 3,
        name: "senran kagura",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: true,
    },
    {
        position: 4,
        name: "new game! 1 y 2",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: true,
    },
    {
        position: 5,
        name: "owari no seraph",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: false,
    },
    {
        position: 6,
        name: "series fate",
        date: "2016",
        description:
            "los animes de esta primera sección no estan ordenados. en el anime crack de pika cheeks",
        has_conclusion: true,
    },
    {
        position: 7,
        name: "dragon ball super",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: true,
    },
    {
        position: 8,
        name: "one punch man",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: true,
    },
    {
        position: 9,
        name: "sword art online",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: false,
    },
    {
        position: 10,
        name: "nanatsu no taizai",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: false,
    },
    {
        position: 11,
        name: "yugioh arc v / 5ds / duel monsters / link vrains",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: true,
    },
    {
        position: 12,
        name: "evangelion",
        date: "2016",
        description: "los animes de esta primera sección no estan ordenados",
        has_conclusion: true,
    },
    {
        position: 13,
        name: "densetsu no yuusho no densetsu (leyenda de los heroes legendarios)",
        date: "vacaciones de verano 2016-2017",
        description: "",
        has_conclusion: false,
    },
    {
        position: 14,
        name: "kono subarashi sekai ni shukufuku wo! / 2",
        date: "vacaciones de verano 2016-2017",
        description: "en el animecrack de pika cheeks",
        has_conclusion: false,
    },
    {
        position: 15,
        name: "hagure yuusha no estetica",
        date: "vacaciones de verano 2016-2017",
        description: "",
        has_conclusion: false,
    },
    {
        position: 16,
        name: "sora no woto",
        date: "vacaciones de verano 2016-2017",
        description: "",
        has_conclusion: true,
    },
    {
        position: 17,
        name: "to aru majutsu no index / to aru kagaku no railgun / accelerator",
        date: "antes de empezar el cbc 2",
        description: "",
        has_conclusion: false,
    },
    {
        position: 18,
        name: "seirei tsukai no blade dance",
        date: "antes de empezar el cbc 2",
        description: "sin final... otra vez...",
        has_conclusion: false,
    },
    {
        position: 19,
        name: "katanagatari",
        date: "antes de empezar el cbc 2",
        description: "",
        has_conclusion: true,
    },
    {
        position: 20,
        name: "gabriel DropOut",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 21,
        name: "akame ga kill",
        date: "(cuando fui a mar del plata en 2017) despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "en el anime crack de pika cheeks",
        has_conclusion: true,
    },
    {
        position: 22,
        name: "tokyo ravens",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 23,
        name: "toradora!",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 24,
        name: "mahouka koukou no rettousei",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "",
        has_conclusion: false,
    },
    {
        position: 25,
        name: "another",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "(antes expandir la lista estos estaban arriba)",
        has_conclusion: true,
    },
    {
        position: 26,
        name: "Chuunibyou demo Koi ga Shitai!",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description:
            "en el anime crack de pika cheeks. (antes expandir la lista estos estaban arriba)",
        has_conclusion: true,
    },
    {
        position: 27,
        name: "mirai nikki",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "(antes expandir la lista estos estaban arriba)",
        has_conclusion: true,
    },
    {
        position: 28,
        name: "kobayashi-san chi no maid dragon",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "(antes expandir la lista estos estaban arriba)",
        has_conclusion: true,
    },
    {
        position: 29,
        name: "shirobako",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "(antes expandir la lista estos estaban arriba)",
        has_conclusion: true,
    },
    {
        position: 30,
        name: "big order",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "(antes expandir la lista estos estaban arriba)",
        has_conclusion: true,
    },
    {
        position: 31,
        name: "campione!",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description: "(antes expandir la lista estos estaban arriba)",
        has_conclusion: true,
    },
    {
        position: 32,
        name: "shakugan no shana",
        date: "despues de empezar el cbc 2 (primer cuatrimestre)",
        description:
            "(antes expandir la lista estos estaban arriba) (la lolita dinamita) 32, PERO MADRE MIA...",
        has_conclusion: true,
    },
    {
        position: 33,
        name: "roku de nashi majutsu koshi to akashic records",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "",
        has_conclusion: false,
    },
    {
        position: 34,
        name: "maho shojo ikusei keikaku",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 35,
        name: "eromanga sensei",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 36,
        name: "zero no tsukaima",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 37,
        name: "Mondaiji-tachi ga Isekai kara Kuru Sou Desu yo?",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 38,
        name: "Re:Creators",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "(6 meses de espera valieron la pena)",
        has_conclusion: true,
    },
    {
        position: 39,
        name: "youjo senki",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "",
        has_conclusion: false,
    },
    {
        position: 40,
        name: "Taimadou Gakuen 35 Shiken Shoutai",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "",
        has_conclusion: false,
    },
    {
        position: 41,
        name: "bakuman!",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre), (la segunda temporada la empecé a ver en la casa d ema 12/10/2017 hasta el 16/10/2017)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 42,
        name: "aldnoah.zero",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "en el anime crack de pika cheeks",
        has_conclusion: true,
    },
    {
        position: 43,
        name: "shiki",
        date: "despues de empezar el cbc 2 (segundo cuatrimestre)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 44,
        name: "steins;gate y steins;gate zero",
        date: "vacaciones de verano 2017-2018",
        description: "en el anime crack de pika cheeks",
        has_conclusion: true,
    },
    {
        position: 45,
        name: "tamako market + tamako love story (pelicula)",
        date: "vacaciones de verano 2017-2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 46,
        name: "lucky star",
        date: "vacaciones de verano 2017-2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 47,
        name: "Ookami-san to Shichinin no Nakama-tachi",
        date: "vacaciones de verano 2017-2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 48,
        name: "Inou-Battle wa Nichijou-kei no Naka de",
        date: "vacaciones de verano 2017-2018",
        description: "",
        has_conclusion: false,
    },
    {
        position: 49,
        name: "Jinrui wa Suitai Shimashita",
        date: "vacaciones de verano 2017-2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 50,
        name: "Machine-Doll wa Kizutsukanai",
        date: "vacaciones de verano 2017-2018, (los ultimos 3 caps. los vi el 23 y 24/12/2017)",
        description: "",
        has_conclusion: false,
    },
    {
        position: 51,
        name: "Bungou Stray Dogs",
        date: "vacaciones de verano 2017-2018",
        description: "",
        has_conclusion: false,
    },
    {
        position: 52,
        name: "sora wo miageru shoujo no hitomi ni utsuru sekai",
        date: "vacaciones de verano 2017-2018",
        description: "(las ovas si que tienen final)",
        has_conclusion: false,
    },
    {
        position: 53,
        name: "Ousama Game The Animation",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 54,
        name: "Net-juu no Susume",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 55,
        name: "Blend-S",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 56,
        name: "Cowboy Bebop + pelicula",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 57,
        name: "Acchi Kocchi",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 58,
        name: "zetsumetsu kigu shoujo amazing twins",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 59,
        name: "Dies Irae",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 60,
        name: "Corpse Party",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 61,
        name: "Kore Wa Zombie Desu Ka? y Of The Dead",
        date: "a partir de 2018",
        description: "",
        has_conclusion: false,
    },
    {
        position: 62,
        name: "Osake wa Fuufu ni Natte kara?",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 63,
        name: "Shuumatsu Nani Shitemasu ka? Isogashii desu ka? Sukutte Morotte Ii desu ka?",
        date: "a partir de 2018",
        description: "puta k sad...",
        has_conclusion: true,
    },
    {
        position: 64,
        name: "Zankyou No Terror o terror in resonance",
        date: "a partir de 2018, (lo empecé en la casa de ema del 5/2/2018 al 13/2/2018)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 65,
        name: "Evil Or Live",
        date: "a partir de 2018",
        description: "felicidades por la primera pantala completada 22/02/2018",
        has_conclusion: true,
    },
    {
        position: 66,
        name: "Death Parade",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 67,
        name: "Arve Rezzle: Kikaijikake no Yoseitachi",
        date: "a partir de 2018",
        description: "(1 solo cap)",
        has_conclusion: false,
    },
    {
        position: 68,
        name: "Little Witch Academia",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 69,
        name: "Sousei no Onmyouji",
        date: "a partir de 2018",
        description: "(que buen anime)",
        has_conclusion: true,
    },
    {
        position: 70,
        name: "Ansatsu Kyoushitsu (assessination classroom)",
        date: "a partir de 2018",
        description: "(final choto T-T))",
        has_conclusion: true,
    },
    {
        position: 71,
        name: "Hitsugi No Chaika",
        date: "a partir de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 72,
        name: "C: The Money of Soul and Possibility Control",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 73,
        name: "YuruYuri",
        date: "aproximadamente a partir de abril de 2018, (durante el horrible periodo sin computadora por culpa de compumundo)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 74,
        name: "Violet Evergarden",
        date: "aproximadamente a partir de abril de 2018",
        description: "(volvi a ver shana antes d ver este el 26/4/18)",
        has_conclusion: true,
    },
    {
        position: 75,
        name: "Hakata Tonkotsu Ramen",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 76,
        name: "K-On!",
        date: "aproximadamente a partir de abril de 2018",
        description: "otro mas q nunca estuvo en la lista de pendientes...)",
        has_conclusion: true,
    },
    {
        position: 77,
        name: "Charlotte",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 78,
        name: "Mahoutsukai No Yome",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 79,
        name: "Konohana Kitan",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 80,
        name: "School Days",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 81,
        name: "Yuru Camp",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 82,
        name: "Angel Beats!",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 83,
        name: "Black Bullet",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: false,
    },
    {
        position: 84,
        name: "Maho Shojo Madoka Magica",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 85,
        name: "Tokyo Magnitude 8.0",
        date: "aproximadamente a partir de abril de 2018, (justo despues de volver de lo de ema el 27/5/18)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 86,
        name: "Dance In The Vampire Bund",
        date: "aproximadamente a partir de abril de 2018",
        description: "",
        has_conclusion: false,
    },
    {
        position: 87,
        name: "Jigoku Shoujo",
        date: "junio 2018",
        description: "(todas las temporadas)",
        has_conclusion: true,
    },
    {
        position: 88,
        name: "Ghost Hound",
        date: "junio 2018",
        description:
            "17/6/18 a partir de aca todas las listas d anime estan en mega",
        has_conclusion: true,
    },
    {
        position: 89,
        name: "Mitsuboshi Colors",
        date: "junio 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 90,
        name: "Nichijou",
        date: "julio 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 91,
        name: "Ga Rei Zero",
        date: "julio 2018",
        description: "",
        has_conclusion: false,
    },
    {
        position: 92,
        name: "Occultic;Nine",
        date: "julio 2018",
        description: "",
        has_conclusion: false,
    },
    {
        position: 93,
        name: "Karakai Jouzu no Takagi-san",
        date: "julio 2018",
        description: "",
        has_conclusion: false,
    },
    {
        position: 94,
        name: "Aho Girl",
        date: "agosto 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 95,
        name: "Inu To Hasami Wa Tsukaiyou",
        date: "agosto 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 96,
        name: "Watamote!",
        date: "agosto 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 97,
        name: "Kokoro Connect + Michi Random",
        date: "agosto 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 98,
        name: "Kantai Collection: KanColle",
        date: "agosto 2018",
        description: "",
        has_conclusion: false,
    },
    {
        position: 99,
        name: "Kara No Kyoukai",
        date: "agosto 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 100,
        name: "91 Days",
        date: "agosto 2018",
        description: "(EL GRAN ANIME NUMERO 100!!!!)",
        has_conclusion: true,
    },
    {
        position: 101,
        name: "Death Note",
        date: "agosto 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 102,
        name: "Grisaia No Kjitsu",
        date: "septiembre 2018",
        description: "(la loli colombiana valió la pena)",
        has_conclusion: true,
    },
    {
        position: 103,
        name: "Kiznaiver",
        date: "septiembre 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 104,
        name: "Ergo Proxy",
        date: "septiembre 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 105,
        name: "3D Kanojo Real Girl",
        date: "septiembre 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 106,
        name: "Amaama To Inazuma",
        date: "septiembre 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 107,
        name: "Hataraku Saibou",
        date: "octubre 2018 (despues de rever 6, 12, 17, 44)",
        description: "",
        has_conclusion: true,
    },
    {
        position: 108,
        name: "Rail Wars!",
        date: "noviembre 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 109,
        name: "Mekaku City Actors",
        date: "noviembre 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 110,
        name: "Suzumiya Haruhi No Yuutsu // Nagato Yuki-chan no Shoushitsu",
        date: "noviembre 2018",
        description: "",
        has_conclusion: true,
    },
    {
        position: 111,
        name: "Zombieland Saga",
        date: "enero 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 112,
        name: "Sakurasou No Pet Na Kanojo",
        date: "enero 2019",
        description: "en el animecrack de pika cheeks",
        has_conclusion: true,
    },
    {
        position: 113,
        name: "Happy Sugar Life",
        date: "enero 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 114,
        name: "Irozuku Sekai No Ashita Kara",
        date: "enero 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 115,
        name: "Barakamon",
        date: "enero 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 116,
        name: "Nejimaki Seirei Senki Tenkyou No Alderamin",
        date: "enero 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 117,
        name: "Btooom!",
        date: "enero 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 118,
        name: "Kaguya-sama Love Is War",
        date: "febrero 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 119,
        name: "Rokka No Yuusha",
        date: "febrero 2019",
        description: "malisimo...",
        has_conclusion: false,
    },
    {
        position: 120,
        name: "Yami Shibai",
        date: "febrero 2019",
        description: "(las 6 temporadas)",
        has_conclusion: true,
    },
    {
        position: 121,
        name: "Kyoukai No Kanata",
        date: "febrero 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 122,
        name: "Yakusoku No Neverland",
        date: "febrero 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 123,
        name: "Kill Me Baby",
        date: "febrero 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 124,
        name: "Hyouka",
        date: "febrero 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 125,
        name: "Isekai Quartet",
        date: "febrero 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 126,
        name: "Overlord",
        date: "febrero 2019, (lo empece en la casa d ema el 18/4/2019 hasta el 22/4/2019)",
        description: "",
        has_conclusion: false,
    },
    {
        position: 127,
        name: "Princess Principal",
        date: "febrero 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 128,
        name: "Joshiraku",
        date: "mayo 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 129,
        name: "Girly Air Force",
        date: "mayo 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 130,
        name: "Tensei Shitara Slime Datta Ken",
        date: "mayo 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 131,
        name: "Dimension W",
        date: "mayo 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 132,
        name: "Mikakunin De Shinkoukei",
        date: "mayo 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 133,
        name: "Uchi No Maid Wa Uzasugiru!",
        date: "mayo 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 134,
        name: "Boogiepop Wa Warawanai",
        date: "mayo 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 135,
        name: "Tate No Yuusha No Nariagari",
        date: "mayo 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 136,
        name: "Boku Dake Ga Inai Machi",
        date: "mayo 2019",
        description: "en el animecrack de pika cheeks",
        has_conclusion: true,
    },
    {
        position: 137,
        name: "Sewayaki Kitsune No Senko-san",
        date: "mayo 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 138,
        name: "Tonari No Kyuuketsuki-san",
        date: "mayo 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 139,
        name: "Danganronpa The Animation",
        date: "mayo 2019",
        description: "(lo empecé con biur)(solo la primera temporada)",
        has_conclusion: false,
    },
    {
        position: 140,
        name: "Isshukan Friends",
        date: "mayo 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 141,
        name: "Watashi Ni Tenshi Ga Miorita!",
        date: "mayo 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 142,
        name: "Marchen Madchen",
        date: "septiembre 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 143,
        name: "Hitoribocchi No ○ ○ Seikatsu",
        date: "septiembre 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 144,
        name: "Gosick",
        date: "septiembre 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 145,
        name: "Yuyushiki",
        date: "octubre 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 146,
        name: "Azur Lane",
        date: "octubre 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 147,
        name: "Kimetsu No Yaiba",
        date: "octubre 2019",
        description: "",
        has_conclusion: false,
    },
    {
        position: 148,
        name: "Maria Holic y Maria Holic Alive",
        date: "octubre 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 149,
        name: "Zero Kara Hajimeru Mahou No Sho",
        date: "noviembre 2019",
        description: "",
        has_conclusion: true,
    },
    {
        position: 150,
        name: "Dumbbell Nan Kilo Moteru?",
        date: "diciembre 2019",
        description: " EL FANTÁSTICO ANIME NÚMERO 150!!!!",
        has_conclusion: true,
    },
    {
        position: 151,
        name: "Monogatari Series",
        date: "enero 2020",
        description: "(completo hasta febrero del 2020)",
        has_conclusion: true,
    },
    {
        position: 152,
        name: "Asobi Asobase",
        date: "febrero 2020",
        description:
            "Me había olvidado de ponerlo, supongo que lo ví después de ver Monogatari",
        has_conclusion: true,
    },
    {
        position: 153,
        name: "Kyokou Surui",
        date: "7 de Mayo 2020, después de terminar la página de Yu-Gi-Oh! Para el pueblo",
        description:
            "(tambien puede sero kyoko surui, aunque asi no se escriba) nada muy destacable, mezcla de comedia y misterio",
        has_conclusion: true,
    },
    {
        position: 154,
        name: "Machikado mazoku",
        date: "Del 12 Al 17 De Mayo 2020",
        description: "Durante La Cuarentena",
        has_conclusion: false,
    },
    {
        position: 155,
        name: "Gate: Jieitai Kanochi Nite, Kaku Tatakaeri",
        date: "Del Viernes 22 Al Viernes 29 De Mayo 2020",
        description: "El Anime Del Portal Y Los Militares",
        has_conclusion: true,
    },
    {
        position: 156,
        name: "NekoPara",
        date: "junio 2020",
        description: "",
        has_conclusion: true,
    },
    {
        position: 157,
        name: "22/7 (Nanabun No Nijyuuni)",
        date: "Del 2 Al 4 De Julio 2020",
        description: "Las Idols Que Trascienden Las Dimensiones",
        has_conclusion: false,
    },
    {
        position: 158,
        name: "Shoujo Shuumatsu Ryokou",
        date: "Del 18 Al 25 Julio 2020",
        description: "Las 2 Lolis Sobreviviendo En El Fin Del Mundo",
        has_conclusion: true,
    },
    {
        position: 159,
        name: "Princess Connect Re:Dive",
        date: "Mier 29 De Julio A Mar 4 De Agosto",
        description: "Rip Off De Kono Suba 10/10",
        has_conclusion: false,
    },
    {
        position: 160,
        name: "Seirei no moribito",
        date: "",
        description:
            "Moribito Guardian of the Spirit. Malísimo, re lento y la historia prácticamente se terminó en el capítulo 5",
        has_conclusion: true,
    },
    {
        position: 161,
        name: "Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta...",
        date: "del 23 al 25 de agosto 2020",
        description: "Buenísimo, 10/10",
        has_conclusion: false,
    },
    {
        position: 162,
        name: "rolling girls",
        date: "desde el 26 de ago, hasta el 6 de sep",
        description:
            "Lo retomé despues de ver seirei moribito y decidir que iba a terminar algunos animes dropeados. Empieza bien, y hasta el cap 9 no avanza la historia.",
        has_conclusion: true,
    },
    {
        position: 163,
        name: "Seikaisuru Kado",
        date: "desde el 11/09/2020 hasta el 12/09/2020",
        description:
            "La animacón da cáncer, la historia empieza espectacular, pero el final es malísimo",
        has_conclusion: true,
    },
    {
        position: 164,
        name: "Uchouten Kazoku",
        date: "desde el 12/09/2020 hasta el 25/09/2020",
        description:
            "El otro anime dropeado que retomé y este si resultó ser bueno. Éste debería haber sido el anime número 158",
        has_conclusion: true,
    },
    {
        position: 165,
        name: "Id:Invaded",
        date: "del 19 al 20 de octubre 2020",
        description: "Malisimo, lleno de huecos argumentales",
        has_conclusion: true,
    },
    {
        position: 166,
        name: "Kanojo, Okarishimasu",
        date: "Lo vi entero el 22/octubre/2020",
        description:
            "Es coincidencialandia, pero es muy bueno, y tiene menos fanservice de lo q esperaba",
        has_conclusion: false,
    },
    {
        position: 167,
        name: "Kakushigoto",
        date: "entre el vie 23 y el sab 24",
        description: "Vine buscando plata y encontré oro",
        has_conclusion: true,
    },
    {
        position: 168,
        name: "gakkou gurashi!",
        date: "El domingo 25 de octubre",
        description:
            "Yo me esperaba un anime de zombies comun y corriente, y boludo... nunca me golpearon tan duro....",
        has_conclusion: true,
    },
    {
        position: 169,
        name: "bofuri la waifu del escudo",
        date: "lo vi entero el 4/11/20",
        description:
            "itai no wa iya nano de bougyoryoku ni kyokufuri shitai to omoimasu. Referencias por montones",
        has_conclusion: false,
    },
    {
        position: 170,
        name: "Darling In The Franxx",
        date: "Del 6 al 7 de noviembre",
        description:
            "Era tan bueno.... Pero resultó ser otro anime arruinado por el cliché.....",
        has_conclusion: true,
    },
    {
        position: 171,
        name: "SSSS.Gridman",
        date: "Del 14/11 al 17/11 de 2020",
        description:
            "Lo vi por los muslos de takarada rikka, al final era un supersentai XD",
        has_conclusion: true,
    },
    {
        position: 172,
        name: "Watashi, nouryoku wa heikichi de tte itta yo ne!",
        date: "Del 21 al 28 de nov 2020",
        description:
            'Muchas referencias por todos lados "la gente muere cuando los asesinan"',
        has_conclusion: false,
    },
    {
        position: 173,
        name: "darker than black",
        date: "se que lo terminé el 27/dic/20",
        description: "",
        has_conclusion: false,
    },
    {
        position: 174,
        name: "Endro~!",
        date: "del 21 al 23 de diciembre 2020",
        description: "",
        has_conclusion: true,
    },
    {
        position: 175,
        name: "Maou Gakuin No Futekigousha",
        date: "lo vi entero el dom 31/01/2021",
        description: "",
        has_conclusion: true,
    },
    {
        position: 176,
        name: "Boku wa tomodachi ga sukunai",
        date: "Desde mediados de enero a mediados de febrero",
        description:
            "Muy ecchi, pero muy bueno LARGA VIDA AL YURI Y A LOS SHIPPEOS!!!",
        has_conclusion: false,
    },
    {
        position: 177,
        name: "Ghost hunt",
        date: "Desde mediados de febrero 21, hasta el 25 de febrero del 21",
        description:
            "Habia una posibilidad de q fuera ESE anime, pero no lo era. Aún así, muy buen anime de suspenso/terror",
        has_conclusion: true,
    },
    {
        position: 178,
        name: "Gakkou No Kaidan",
        date: "se perdió en el tiempo...",
        description:
            "ES ESEEEEEEE !!!!!!!!!! POR FINNNNNNNNN!!!!!!!! DESPUES DE TANTO TIEMPOOOOOOO!!!!!!!!!",
        has_conclusion: true,
    },
    {
        position: 179,
        name: "Non Non Biyori",
        date: "Se perdió en el tiempo...",
        description:
            "Lo descargué y lo vi con esta vieja estupida mientras salía la 4ta temporada",
        has_conclusion: true,
    },
    {
        position: 180,
        name: "Wotakoi - Wotaku Ni Koi Wa Muzukashii",
        date: "Ee perdió en el tiempo...",
        description: "",
        has_conclusion: true,
    },
    {
        position: 181,
        name: "Ani Ni Tsukeru Kusuri Wa Nai",
        date: "Se perdió en el tiempo...",
        description:
            "La canción está en la 2da temp, cap 9. Buenísimo, aunque los capitulos duren solo 3 minutos... Lo ví después de intentar ver Meteoro",
        has_conclusion: true,
    },
    {
        position: 182,
        name: "Comic Girls",
        date: "Se perdió en el tiempo....",
        description: "",
        has_conclusion: true,
    },
    {
        position: 183,
        name: "The God Of Highschool",
        date: "Lo ví entero el 1/6/21",
        description: "Muy buena mezcla de culturas",
        has_conclusion: false,
    },
    {
        position: 184,
        name: "Shinchou Yuusha Kono Yuusha Ga Ore Tueee Kuse Ni Shinchou Sugiru",
        date: "Entre el 21 y 22 de junio 2021",
        description: "",
        has_conclusion: true,
    },
    {
        position: 185,
        name: "Mars Red",
        date: "Del 28/6 al 1/7 del 2021",
        description:
            "La animación no era muy buena, nunca entendi muy bien la historia, pero estuvo bueno, creo",
        has_conclusion: true,
    },
    {
        position: 186,
        name: "Odd Taxi",
        date: "del 2 al 10 de julio 2021",
        description: "Lo vi con esta vieja estupida, muy bueno 10/10",
        has_conclusion: true,
    },
    {
        position: 187,
        name: "Noragami",
        date: "entre el 26 de agosto y el 3 de septiembre 2021",
        description:
            "Lo vi con esta vieja estúpida. Nunca me llamó la atención, y resultó ser muy bueno",
        has_conclusion: false,
    },
    {
        position: 188,
        name: "majo no tabitabi",
        date: "la semana del 10 de sep de 2021",
        description: "Para variar, uno más que no estaba en la lista...",
        has_conclusion: false,
    },
    {
        position: 189,
        name: "shakunetsu kabaddi",
        date: "lo vi entero el dom 12/09/21",
        description: "Alias: Burning Kabaddi",
        has_conclusion: false,
    },
    {
        position: 190,
        name: "86",
        date: "la semana del 17 de sep de 2021",
        description:
            "También conocido como Eighty Six, lo ví con esta vieja estúpida un mes antes de la 2da temp, así que no se si tiene final o no",
        has_conclusion: true,
    },
    {
        position: 191,
        name: "Robotic;Notes",
        date: "Semana del 20 / 09 / 21",
        description:
            "En el mismo mundo de Steins;Gate. Tiene la canción de un video de fate",
        has_conclusion: true,
    },
    {
        position: 192,
        name: "jahy sama",
        date: "lo vi mientras estaba en emisión, sep 2021",
        description: "",
        has_conclusion: true,
    },
    {
        position: 193,
        name: "Gekkan Shoujo Nozaki-Kun",
        date: "El domingo 21 de noviembre de 2021",
        description:
            "Es el q recomendó julia, con buen diseño de personajes, pero un final re choto",
        has_conclusion: false,
    },
    {
        position: 194,
        name: "Heion Seidan No Idaten Tachi",
        date: "Durante las refacciones de la página web.",
        description: "Simplemente buenisimo, y muy TENTADOR.",
        has_conclusion: false,
    },
    {
        position: 195,
        name: "Urasekai Picnic",
        date: "Durante las refacciones de la página web.",
        description:
            "El de las 2 chicas que van al mundo de las leyendas urbanas.",
        has_conclusion: true,
    },
    {
        position: 196,
        name: "Bokutachi Wa Benkyou Ga Dekimasen",
        date: "Durante las refacciones de la página web.",
        description: "El de los memes de la peliazul.",
        has_conclusion: true,
    },
    {
        position: 197,
        name: "Tower Of God",
        date: "Durante las refacciones de la página web.",
        description: "La traición al final se veía venir, en mi opinión...",
        has_conclusion: false,
    },
    {
        position: 198,
        name: "Gochuumon Wa Usagi Desu Ka?",
        date: "Durante las refacciones de la página web.",
        description: "El de las lolis bailando en el ending.",
        has_conclusion: true,
    },
    {
        position: 199,
        name: "Mahou Shoujo Site",
        date: "Durante las refacciones de la página web.",
        description: "",
        has_conclusion: false,
    },
    {
        position: 200,
        name: "Fullmetal Alchemist & Brotherhood",
        date: "Durante las refacciones de la página web.",
        description: "No vale la pena, 6/10.",
        has_conclusion: true,
    },
    {
        position: 201,
        name: "Akiba's Trip: The Animation",
        date: "La semana del 10 de feb del 2022",
        description: "Malisimo, muy olvidable, nada q ver con zombieland saga",
        has_conclusion: true,
    },
    {
        position: 202,
        name: "Fuumetsu No Anata E",
        date: "La semana del 19 de feb de 2022",
        description: "BOLUDO QUE FAQUIN TRSITEEE",
        has_conclusion: false,
    },
    {
        position: 203,
        name: "Kaifuku jutsushi no yarinaoshi",
        date: "Lo vi entero el 20/2/2022",
        description: "ZKULEMTO...",
        has_conclusion: false,
    },
    {
        position: 204,
        name: "Black Lagoon",
        date: "Desde el 21 de feb, al 1 de mar 2022",
        description: "",
        has_conclusion: true,
    },
    {
        position: 205,
        name: "Slime Taoshite 300-Nen, shiranai uchi ni level max ni natteshimashita",
        date: "Entre el 1 y 2 de mar 2022",
        description: "El anime del slime.... No, el otro anime del slime",
        has_conclusion: true,
    },
    {
        position: 206,
        name: "mushoku tensei: isekai ittara honki desu",
        date: "Desde el sabado 5 al lunes 7 de mar del 2022",
        description: "",
        has_conclusion: false,
    },
    {
        position: 207,
        name: "Strike The Blood",
        date: "principios de 2022",
        description:
            "Nunca lo terminé realmente de ver, pero me ví 3 temporadas, así que yo supongo que cuenta...",
        has_conclusion: true,
    },
    {
        position: 208,
        name: "Spy X Family",
        date: "principios de 2022",
        description:
            "Este lo vi en las otaku no yoru con chibi, lau, y nico (del curso de japonés)",
        has_conclusion: true,
    },
    {
        position: 209,
        name: "Paripi Koumei",
        date: "30/06/2022",
        description:
            "Lo vi entero en un solo día, en el departamento de kyoto apartment",
        has_conclusion: false,
    },
    {
        position: 210,
        name: "Gamers!",
        date: "lo vi entero la noche del 3 al 4 de julio 2022",
        description: "Este era uno de esos que salian en los anime cracks",
        has_conclusion: false,
    },
    {
        position: 211,
        name: "Hataraku maou-sama!",
        date: "en algun punto de septiembre 2022",
        description:
            "Lo vi descargado y justo estaba saliendo la 2da temporada, así que la vi en emisión. Y luego salió la 3er temporada, la cual también vi y la terminé estando ya en argentina de vuelta",
        has_conclusion: false,
    },
    {
        position: 212,
        name: "gundam (la serie original)",
        date: "en algún punto durante el viaje a japón",
        description: "",
        has_conclusion: true,
    },
    {
        position: 213,
        name: "kami-sama hajimemashita",
        date: "Lo vi mientras veía gundam en noviembre 2022",
        description: "está en el mismo mundo del noragami original",
        has_conclusion: true,
    },
    {
        position: 214,
        name: "gundam: suisei no majo",
        date: "2022 - hasta que lo dropeé despues de volver a Arg",
        description:
            "Le tenia muchas expectativas a este y resultó ser malísimo...",
        has_conclusion: true,
    },
    {
        position: 215,
        name: "Lycoris Recoil",
        date: "Lo vi entero el 31/12/22",
        description: "La espera valió cada maldito segundo.",
        has_conclusion: false,
    },
    {
        position: 216,
        name: "Bocchi The Rock!",
        date: "Lo vi entero la noche del 1 al 2 de marzo 2022",
        description: "Valió cada maldito segundo también, ES BUENÍSIMO!!!",
        has_conclusion: true,
    },
    {
        position: 217,
        name: "SSSS.Dynazenon",
        date: "Lo vi entre el lunes 27 de marzo 2023, al domingo 2 de abril",
        description: "Lo vi después de haber visto la peli de Gridman",
        has_conclusion: true,
    },
    {
        position: 218,
        name: "Mob Psycho",
        date: "Lo vi con ema por discord entre marzo y el 26 de mayo de 2023",
        description: "",
        has_conclusion: true,
    },
    {
        position: 219,
        name: "Chainsaw Man",
        date: "Lo vi el viernes 26/5 y el sábado 3/6 2023 con ema por discord",
        description:
            "El pibe motosierra no era tan malo al final, yo pensé que iba a ser peor jajajaj",
        has_conclusion: false,
    },
    {
        position: 220,
        name: "Amagi Brilliant Park",
        date: "Lo vi del 10 al 13 de julio 2023 n lo de ema en mardel",
        description: "Contienen referencias... Rikolinas XD",
        has_conclusion: false,
    },
    {
        position: 221,
        name: "Tensai Ouji No Akaji Kokka Saisei Jutsu",
        date: "Lo empecé con ema en mardel el 12 de julio en mardel, hasta el 26 de ago del 2023",
        description:
            "La protagonista  (que tiene buen diseño) yambién tiene la voz de Mash",
        has_conclusion: false,
    },
    {
        position: 222,
        name: "Girls Frontline",
        date: "Lo vi con ema por discord entre el 26/08 y el 3/9",
        description: "FGO era mejor XD",
        has_conclusion: false,
    },
    {
        position: 223,
        name: "Onii-chan Wa Oshimai!",
        date: "Lo vi el viernes 13 y sábado 14 de octubre 2023",
        description:
            "Me esperaba mucho más fan service y referencias sinceramente XD",
        has_conclusion: true,
    },
    {
        position: 224,
        name: "Yokohama Kaidashi Kikou",
        date: "Lo vi entero el 16/10/2023 (el dia después del dia de la madre)",
        description:
            "Son 2 capítulos nomás. No hay historia, una robot kawaii que sirve café en un pueblito post-apocalíptico",
        has_conclusion: true,
    },
    {
        position: 225,
        name: "RWBY The Ice Queendom",
        date: "Lo vi el fin de semana de las elecciones (21 y 22 de octubre 2023)",
        description:
            '"Qué estás haciendo?" "Viendo 2 waifus pelear con un pan" "Querrás decir peleando POR un pan, no?" "Nono, peleando CON un pan"',
        has_conclusion: false,
    },
    {
        position: 226,
        name: "Yofukashi No Uta",
        date: "Del 26 al 27 de octubre 2023",
        description:
            "Nada en particular para destacar, del mismo creador de la tienda de dulces",
        has_conclusion: false,
    },
    {
        position: 227,
        name: "Kami-Sama Ni Natta Hi",
        date: "Lo vi entero el sábado 28/10/2023",
        description:
            "Sinceramente, no parece haber sido escrito por el mismo creador de Clannad, Angel Beats!, y Charlotte... Parece más que fue escrito por un empresaurio o un alieníjena XD",
        has_conclusion: true,
    },
    {
        position: 228,
        name: "Arknights",
        date: "Lo vi entre el 29 y el 31 de octubre 2023 y hasta que se terminó de emitir la 2da temp",
        description:
            "Prelude Of Dawn y Perish In The Frost. Boludo, que buena animación, parece un tráiler de 8 capítulos... Aparte, la historia recién se puso buena a partir de la mitad T-T // En la segunda temporada volvió a pasar lo mismo...",
        has_conclusion: false,
    },
    {
        position: 229,
        name: "Parasite",
        date: "Desde el 4 de noviembre al 3 de diciembre (aunque no estoy del todo seguro)",
        description: "Muy buena premisa, final malísimo... Para variar...",
        has_conclusion: true,
    },
    {
        position: 230,
        name: "Kawaii Dake Ja Nai Shikimori-San",
        date: "Lo vi en navidad, 24 y 25 de diciembre 2023",
        description:
            "Está bueno para apagar el cerebro y pasar el rato, pero me frustró mucho el final jajaj",
        has_conclusion: true,
    },
    {
        position: 231,
        name: "Mieruko-Chan",
        date: "29/12 -> 30/12 de 2023",
        description:
            "Me sorprendió gratamente lo muy bueno que resultó ser... PERO NECESITO MÁS FANSERVICEEEEEE!!!",
        has_conclusion: false,
    },
    {
        position: 232,
        name: "Aharen-San Wa Hakarenai",
        date: "del 31/12/23 al 1/1/24",
        description: "*sonido de tijeras*",
        has_conclusion: false,
    },
    {
        position: 233,
        name: "Jujutsu Kaisen",
        date: "Lo vi entre el 13 y el 16 de febrero 2024",
        description: "Es básicamente Naruto XD",
        has_conclusion: false,
    },
    {
        position: 234,
        name: "Sousou No Frieren",
        date: "Del sabado 30 de marzo hasta el viernes 5 de abril",
        description:
            "Lo ví justo despues de que me rechazó Chibi Juli el 26 de marzo...",
        has_conclusion: false,
    },
    {
        position: 235,
        name: "Masamune-kun No Revenge",
        date: "Lo vi entero el Dom 21 de Abr. 2024",
        description:
            "Está bueno, pero es una mierda que Adagaki Aki no se enteró de quien era realmente el pibe...",
        has_conclusion: false,
    },
    {
        position: 236,
        name: "Serial Experiments Lain",
        date: "Desde el Viernes 6 de Septiembre al Viernes 27, 2024",
        description: "Lo empecé con ema, pero el dropeó a mitad de camino",
        has_conclusion: true,
    },
    {
        position: 237,
        name: "Shika Nokonoko Koshi Tantan",
        date: "Desde algun punto de la semana del 22 de julio al 21 de octubre del 24",
        description:
            "shikanokonokokoshitantan shikanokonokokoshitantan shikanokonokokoshitantan shikanokonokokoshitantan shikanokonokokoshitantan shikanokonokokoshitantan",
        has_conclusion: true,
    },
    {
        position: 238,
        name: "Dungeon Meshi",
        date: "Del 18 de Octubre al 30 de Noviembre del 2024",
        description: "Dungeon meshi... AHHH DUNGEON MESHI",
        has_conclusion: false,
    },
    {
        position: 239,
        name: "Isekai Maou To Shoukan Shoujo No Dorei Majutsu",
        date: "Del viernes 6 al martes 10 de Diciembre 2024",
        description: "Hubiera estado mejor si era un seinen y listo",
        has_conclusion: false,
    },
    {
        position: 240,
        name: "Uramichi Onii-San",
        date: "Desde el 27 al 31 de diciembre 2024",
        description: "El oniisan depresido",
        has_conclusion: true,
    },
    {
        position: 241,
        name: "Dandadan",
        date: "Vi la primera mitad con ema y biur desde el 14 al 16 de febrero",
        description:
            "POR FIN ME PUEDO SENTIR IDENTIFICADO CON UN ANIME DE ROMANCEEEEEE!!!!!!!!",
        has_conclusion: false,
    },
    {
        position: 242,
        name: "Kage No Jitsuryokusha Ni Naritakute",
        date: "desde el 1 al 23 de marzo 2025",
        description:
            "The eminence in the shadows. Que final prolonga, y la segunda temporada estuvo muy apurada me parece...",
        has_conclusion: false,
    },
    {
        position: 243,
        name: "Girls Und Panzer",
        date: "Marzo a Noviembre de 2025",
        description: "El de las lolis rusas en tanques",
        has_conclusion: false,
    },
];

export async function seedAnimes(strapi: Core.Strapi): Promise<void> {
    const animeService = strapi.service("api::anime.anime");

    if (!animeService) {
        console.error("❌ Anime service not found");
        return;
    }

    try {
        const existingAnimes = await animeService.find({
            pagination: {
                limit: 1,
            },
        });

        if (existingAnimes.results && existingAnimes.results.length > 0) {
            console.log("ℹ️  Animes already exist, skipping seed");
            return;
        }

        console.log("🌱 Seeding animes...");

        for (const animeData of animeSeeds) {
            await animeService.create({
                data: animeData,
            });
            console.log(`  ✅ Created anime: ${animeData.name}`);
        }

        console.log(`🎉 Successfully seeded ${animeSeeds.length} animes`);
    } catch (error) {
        console.error("❌ Error seeding animes:", error);
        throw error;
    }
}
