import { Coordinates } from "./types";

export const initialRotationState = {
    isDragging: false,
    startX: 0,
    startY: 0,
    offsetX: 0,
    offsetY: 0,
};

// Animation configuration
export const ANIMATION_DURATION = 1000;
export const BASE_SCALE = 250;
export const MOBILE_BASE_SCALE = 150;
export const ZOOM_FACTOR = 1.2; // Multiplier for zoomed in state (prevents over-zooming)

// Sensitivity and rotation
export const sensitivity = 75;
export const mobileSensitivity = 50;

// Colors of Chaldeas
export const countryColor = "#e0e0e0";
export const oceanColor = "#bdbdbd";
export const selectedColor = "#29b6f6";

export const strokeWidth = 0.3;
export const thinnerStrokeWidth = "0.2";
export const strokeColor = "black";
export const opacity = 0.8;

export const center: Coordinates = [0, 0];
export const rotate: Coordinates = [0, -30];

export const selectableCountries = [
    "Angola",
    "Albania",
    "United Arab Emirates",
    "Argentina",
    "Armenia",
    "Antarctica",
    "French Southern and Antarctic Lands",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Burundi",
    "Belgium",
    "Benin",
    "Burkina Faso",
    "Bangladesh",
    "Bulgaria",
    "The Bahamas",
    "Bosnia and Herzegovina",
    "Belarus",
    "Belize",
    "Bolivia",
    "Brazil",
    "Brunei",
    "Bhutan",
    "Botswana",
    "Central African Republic",
    "Canada",
    "Switzerland",
    "Chile",
    "China",
    "Ivory Coast",
    "Cameroon",
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Northern Cyprus",
    "Cyprus",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Egypt",
    "Eritrea",
    "Spain",
    "Estonia",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "France",
    "Gabon",
    "England",
    "Georgia",
    "Ghana",
    "Guinea",
    "Gambia",
    "Guinea Bissau",
    "Equatorial Guinea",
    "Greece",
    "Greenland",
    "Guatemala",
    "Guyana",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "India",
    "Ireland",
    "Iran",
    "Iraq",
    "Iceland",
    "Israel",
    "Italy",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kazakhstan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "South Korea",
    "Kosovo",
    "Kuwait",
    "Laos",
    "Lebanon",
    "Liberia",
    "Libya",
    "Sri Lanka",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Morocco",
    "Moldova",
    "Madagascar",
    "Mexico",
    "Macedonia",
    "Mali",
    "Myanmar",
    "Montenegro",
    "Mongolia",
    "Mozambique",
    "Mauritania",
    "Malawi",
    "Malaysia",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "New Zealand",
    "Oman",
    "Pakistan",
    "Panama",
    "Peru",
    "Philippines",
    "Papua New Guinea",
    "Poland",
    "Puerto Rico",
    "North Korea",
    "Portugal",
    "Paraguay",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Western Sahara",
    "Saudi Arabia",
    "Sudan",
    "South Sudan",
    "Senegal",
    "Solomon Islands",
    "Sierra Leone",
    "El Salvador",
    "Somaliland",
    "Somalia",
    "Republic of Serbia",
    "Suriname",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Swaziland",
    "Syria",
    "Chad",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Turkmenistan",
    "East Timor",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "United Republic of Tanzania",
    "Uganda",
    "Ukraine",
    "Uruguay",
    "USA",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Vanuatu",
    "West Bank",
    "Yemen",
    "South Africa",
    "Zambia",
    "Zimbabwe",
];
