import "@salvatore.hakase/log-data";
import { FeatureNames } from "@salvatore.hakase/log-data";

export const FeatureFlagsAvailable = {
    ...FeatureNames,
    CONSUME_STRAPI_DATA: "CONSUME_STRAPI_DATA",
    CONSUME_NAS_FILES: "CONSUME_NAS_FILES",
    SERVE_MOCK_DATA: "SERVE_MOCK_DATA",
    CONSOLE_LOG_ALL_LAYERS: "CONSOLE_LOG_ALL_LAYERS",
    CONSOLE_LOG_LAYER_SPECIFIC: "CONSOLE_LOG_LAYER_SPECIFIC",
    ENABLE_USERS_LOGIN: "ENABLE_USERS_LOGIN",
    ENABLE_USERS_REGISTER: "ENABLE_USERS_REGISTER",
    LOG_EXTERNAL_HTTP_REQUESTS: "LOG_EXTERNAL_HTTP_REQUESTS",
    LOG_INTERNAL_HTTP_REQUESTS: "LOG_INTERNAL_HTTP_REQUESTS",
    LOG_RESPONSE_EXTERNAL_HTTP_REQUEST: "LOG_RESPONSE_EXTERNAL_HTTP_REQUEST",
    LOG_RESPONSE_BODY_EXTERNAL_HTTP_REQUEST:
        "LOG_RESPONSE_BODY_EXTERNAL_HTTP_REQUEST",
    EXPERIMENTAL_VIDEO_PLAYER: "EXPERIMENTAL_VIDEO_PLAYER",
    ENABLE_STREAMING_PROXY: "ENABLE_STREAMING_PROXY",
    CACHE_MEMORY: "CACHE_MEMORY",
} as const;

export type FeatureFlagsAvailable =
    (typeof FeatureFlagsAvailable)[keyof typeof FeatureFlagsAvailable];
