const fs = require("fs");
const path = require("path");

const sdkDir = path.join(
    __dirname,
    "../packages/platform-service-sdk/generated-sdk"
);

console.log("Patching SDK types...");
console.log(" ");

const clientGenPath = path.join(sdkDir, "client.gen.ts");

if (fs.existsSync(clientGenPath)) {
    let clientContent = fs.readFileSync(clientGenPath, "utf8");

    const updatedContent = clientContent.replace(
        /import \{ createClientConfig \} from ["']\.\/packages\/platform-service-sdk\/runtime-config\.ts["'];/,
        'import { createClientConfig } from "../runtime-config";'
    );

    if (updatedContent !== clientContent) {
        fs.writeFileSync(clientGenPath, updatedContent);
        console.log("- Patched client runtime-config import path");
        console.log(" ");
    }
} else {
    console.log("X - client.gen.ts not found, skipping client patch");
    console.log(" ");
}

const typesGenPath = path.join(sdkDir, "types.gen.ts");

if (fs.existsSync(typesGenPath)) {
    let typesContent = fs.readFileSync(typesGenPath, "utf8");
    let wasPatched = false;

    if (!typesContent.includes("@repo/type-definitions")) {
        typesContent = typesContent.replace(
            /\/\/ This file is auto-generated by @hey-api\/openapi-ts\n/,
            `// This file is auto-generated by @hey-api/openapi-ts\n\nimport type { QueryParams } from "@repo/type-definitions";\n`
        );
        wasPatched = true;
        console.log(
            "- Added import for QueryParams from @repo/type-definitions"
        );
        console.log(" ");
    }

    const filtersPattern =
        /filters\?\s*:\s*\{\s*\[key:\s*string\]\s*:\s*unknown;\s*\};/g;
    if (filtersPattern.test(typesContent)) {
        typesContent = typesContent.replace(
            filtersPattern,
            'filters?: QueryParams["filters"];'
        );
        wasPatched = true;
        console.log(
            "- Replaced generic filters type with QueryParams['filters']"
        );
        console.log(" ");
    }

    const paginationPattern =
        /pagination\?\s*:\s*\{\s*withCount\?\s*:\s*boolean;\s*\}\s*&\s*\(\s*\|\s*\{\s*page:\s*number;\s*pageSize:\s*number;\s*\}\s*\|\s*\{\s*start:\s*number;\s*limit:\s*number;\s*\}\s*\);/g;
    if (paginationPattern.test(typesContent)) {
        typesContent = typesContent.replace(
            paginationPattern,
            'pagination?: QueryParams["pagination"];'
        );
        wasPatched = true;
        console.log(
            "- Replaced generic pagination type with QueryParams['pagination']"
        );
        console.log(" ");
    }

    const sortPattern =
        /sort\?:\s*(?:\|\s*)?"[^"]+\"(?:\s*\|\s*"[^"]+\")*\s*\|\s*Array<[^>]+>\s*\|\s*\{[^}]+\}\s*\|\s*Array<\{[^}]+\}>;/gs;
    const sortMatches = typesContent.match(sortPattern);
    if (sortMatches && sortMatches.length > 0) {
        typesContent = typesContent.replace(
            sortPattern,
            'sort?: QueryParams["sort"];'
        );
        wasPatched = true;
        console.log(
            `- Replaced ${sortMatches.length} generic sort type(s) with QueryParams['sort']`
        );
        console.log(" ");
    }

    const populatePattern = /populate\?\s*:\s*"\*"\s*\|[^;]+;/gs;
    const populateMatches = typesContent.match(populatePattern);
    if (populateMatches && populateMatches.length > 0) {
        typesContent = typesContent.replace(
            populatePattern,
            'populate?: QueryParams["populate"];'
        );
        wasPatched = true;
        console.log(
            `- Replaced ${populateMatches.length} generic populate type(s) with QueryParams['populate']`
        );
        console.log(" ");
    }

    const fieldsPattern = /fields\?\s*:\s*string\s*\|\s*Array<string>;/g;
    const fieldsMatches = typesContent.match(fieldsPattern);
    if (fieldsMatches && fieldsMatches.length > 0) {
        typesContent = typesContent.replace(
            fieldsPattern,
            'fields?: QueryParams["fields"];'
        );
        wasPatched = true;
        console.log(
            `- Replaced ${fieldsMatches.length} generic fields type(s) with QueryParams['fields']`
        );
        console.log(" ");
    }

    if (wasPatched) {
        fs.writeFileSync(typesGenPath, typesContent);
        console.log("- Patched types.gen.ts with robust types");
        console.log(" ");
    } else {
        console.log("No type patches needed in types.gen.ts...");
        console.log(" ");
    }
} else {
    console.log("X - types.gen.ts not found, skipping types patch");
    console.log(" ");
}

// Patch sdk.gen.ts to remove local querySerializer configurations
const sdkGenPath = path.join(sdkDir, "sdk.gen.ts");

if (fs.existsSync(sdkGenPath)) {
    let sdkContent = fs.readFileSync(sdkGenPath, "utf8");

    // Count occurrences before replacement
    const querySerializerMatches = sdkContent.match(/querySerializer:\s*\{/g);
    const initialCount = querySerializerMatches
        ? querySerializerMatches.length
        : 0;

    // Remove querySerializer configuration - improved pattern to match multiline
    let updatedSdkContent = sdkContent.replace(
        /querySerializer:\s*\{[\s\S]*?parameters:[\s\S]*?\},\s*\n/g,
        ""
    );

    // Clean up any orphaned closing braces and commas
    updatedSdkContent = updatedSdkContent.replace(
        /\(\{\s+\},\n\s+url:/g,
        "({\n        url:"
    );

    const finalMatches = updatedSdkContent.match(/querySerializer:\s*\{/g);
    const finalCount = finalMatches ? finalMatches.length : 0;
    const removedCount = initialCount - finalCount;

    if (removedCount > 0) {
        fs.writeFileSync(sdkGenPath, updatedSdkContent);
        console.log(
            `✓ Removed ${removedCount} local querySerializer configuration(s) from sdk.gen.ts`
        );
        console.log(" ");
    } else {
        console.log("- No querySerializer patches needed in sdk.gen.ts");
        console.log(" ");
    }
} else {
    console.log("X - sdk.gen.ts not found, skipping sdk patch");
    console.log(" ");
}

// Patch client/utils.gen.ts to use qs for query serialization
const clientUtilsPath = path.join(sdkDir, "client/utils.gen.ts");

if (fs.existsSync(clientUtilsPath)) {
    let utilsContent = fs.readFileSync(clientUtilsPath, "utf8");

    // Add qs import at the top of the file
    if (!utilsContent.includes('import qs from "qs"')) {
        utilsContent = utilsContent.replace(
            /^(\/\/ This file is auto-generated.*\n)/,
            '$1\nimport qs from "qs";\n'
        );
        console.log("✓ Added qs import to client/utils.gen.ts");
    }

    // Replace the createQuerySerializer function with a simple qs wrapper
    const createQuerySerializerPattern =
        /export const createQuerySerializer = <T = unknown>\([^)]*\) => \{[\s\S]*?return querySerializer;\s*\};/;

    if (createQuerySerializerPattern.test(utilsContent)) {
        utilsContent = utilsContent.replace(
            createQuerySerializerPattern,
            `export const createQuerySerializer = <T = unknown>(
    _options?: QuerySerializerOptions
) => {
    const querySerializer = (queryParams: T) => {
        return qs.stringify(queryParams);
    };
    return querySerializer;
};`
        );
        console.log(
            "✓ Replaced createQuerySerializer to use qs in client/utils.gen.ts"
        );
        console.log(" ");
    } else {
        console.log(
            "X createQuerySerializer pattern not found in client/utils.gen.ts"
        );
        console.log(" ");
    }

    fs.writeFileSync(clientUtilsPath, utilsContent, "utf8");
} else {
    console.log("X - client/utils.gen.ts not found, skipping utils patch");
    console.log(" ");
}

console.log("🎉 SDK patching complete!");
