const fs = require("fs");
const path = require("path");

const sdkDir = path.join(
    __dirname,
    "../packages/platform-service-sdk/generated-sdk"
);

console.log("Patching SDK types...");
console.log(" ");

const clientGenPath = path.join(sdkDir, "client.gen.ts");

if (fs.existsSync(clientGenPath)) {
    let clientContent = fs.readFileSync(clientGenPath, "utf8");

    const updatedContent = clientContent.replace(
        /import \{ createClientConfig \} from ["']\.\/packages\/platform-service-sdk\/runtime-config\.ts["'];/,
        'import { createClientConfig } from "../runtime-config";'
    );

    if (updatedContent !== clientContent) {
        fs.writeFileSync(clientGenPath, updatedContent);
        console.log("- Patched client runtime-config import path");
        console.log(" ");
    }
} else {
    console.log("X - client.gen.ts not found, skipping client patch");
    console.log(" ");
}

const typesGenPath = path.join(sdkDir, "types.gen.ts");

if (fs.existsSync(typesGenPath)) {
    let typesContent = fs.readFileSync(typesGenPath, "utf8");
    let wasPatched = false;

    if (!typesContent.includes("@repo/type-definitions")) {
        typesContent = typesContent.replace(
            /\/\/ This file is auto-generated by @hey-api\/openapi-ts\n/,
            `// This file is auto-generated by @hey-api/openapi-ts\n\nimport type { QueryParams } from "@repo/type-definitions";\n`
        );
        wasPatched = true;
        console.log(
            "- Added import for QueryParams from @repo/type-definitions"
        );
        console.log(" ");
    }

    const filtersPattern =
        /filters\?\s*:\s*\{\s*\[key:\s*string\]\s*:\s*unknown;\s*\};/g;
    if (filtersPattern.test(typesContent)) {
        typesContent = typesContent.replace(
            filtersPattern,
            'filters?: QueryParams["filters"];'
        );
        wasPatched = true;
        console.log(
            "- Replaced generic filters type with QueryParams['filters']"
        );
        console.log(" ");
    }

    const paginationPattern =
        /pagination\?\s*:\s*\{\s*withCount\?\s*:\s*boolean;\s*\}\s*&\s*\(\s*\|\s*\{\s*page:\s*number;\s*pageSize:\s*number;\s*\}\s*\|\s*\{\s*start:\s*number;\s*limit:\s*number;\s*\}\s*\);/g;
    if (paginationPattern.test(typesContent)) {
        typesContent = typesContent.replace(
            paginationPattern,
            'pagination?: QueryParams["pagination"];'
        );
        wasPatched = true;
        console.log(
            "- Replaced generic pagination type with QueryParams['pagination']"
        );
        console.log(" ");
    }

    const sortPattern =
        /sort\?:\s*(?:\|\s*)?"[^"]+\"(?:\s*\|\s*"[^"]+\")*\s*\|\s*Array<[^>]+>\s*\|\s*\{[^}]+\}\s*\|\s*Array<\{[^}]+\}>;/gs;
    const sortMatches = typesContent.match(sortPattern);
    if (sortMatches && sortMatches.length > 0) {
        typesContent = typesContent.replace(
            sortPattern,
            'sort?: QueryParams["sort"];'
        );
        wasPatched = true;
        console.log(
            `- Replaced ${sortMatches.length} generic sort type(s) with QueryParams['sort']`
        );
        console.log(" ");
    }

    const populatePattern = /populate\?\s*:\s*"\*"\s*\|[^;]+;/gs;
    const populateMatches = typesContent.match(populatePattern);
    if (populateMatches && populateMatches.length > 0) {
        typesContent = typesContent.replace(
            populatePattern,
            'populate?: QueryParams["populate"];'
        );
        wasPatched = true;
        console.log(
            `- Replaced ${populateMatches.length} generic populate type(s) with QueryParams['populate']`
        );
        console.log(" ");
    }

    const fieldsPattern = /fields\?\s*:\s*string\s*\|\s*Array<string>;/g;
    const fieldsMatches = typesContent.match(fieldsPattern);
    if (fieldsMatches && fieldsMatches.length > 0) {
        typesContent = typesContent.replace(
            fieldsPattern,
            'fields?: QueryParams["fields"];'
        );
        wasPatched = true;
        console.log(
            `- Replaced ${fieldsMatches.length} generic fields type(s) with QueryParams['fields']`
        );
        console.log(" ");
    }

    if (wasPatched) {
        fs.writeFileSync(typesGenPath, typesContent);
        console.log("- Patched types.gen.ts with robust types");
        console.log(" ");
    } else {
        console.log("No type patches needed in types.gen.ts...");
        console.log(" ");
    }
} else {
    console.log("X - types.gen.ts not found, skipping types patch");
    console.log(" ");
}

console.log("🎉 SDK patching complete!");
