import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box } from "@mui/material";
import { ThemeRegistry } from "@/components/ThemeRegistry";

import ToggleSound from "@/components/ToggleSound";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ThemeRegistry>
                <body className={inter.className}>
                    <Box
                        sx={{
                            display: "flex",
                            flexDirection: "column",
                            minHeight: "100vh",
                        }}
                    >
                        <Box component="main" sx={{ flexGrow: 1 }}>
                            {children}
                        </Box>
                    </Box>
                    <ToggleSound />
                </body>
            </ThemeRegistry>
        </html>
    );
}
